golang-1-linux/go.linux-amd64.tar.gz:
  size: 19
  sha: sha256:b16e15764b8bc06c5c3f9f19bc8b99fa48e7894aa5a6ccdad65da49bbf564793
rootfs/cflinuxfs5-0.2.0-beta.tar.gz:
  size: 482390217
  sha: sha256:d8f8b9630c97fd8e7ea58dcaa9d7e414a8bdcb49c31d6841d20ae689f04c44a6
